#!/usr/share/ucs-test/runner python
## desc: Create DHCP shared subnet with wrong superordinate
## tags: [udm-dhcp]
## bugs: [31519]
## roles: [domaincontroller_master]
## exposure: careful
## packages:
##   - univention-config
##   - univention-directory-manager-tools



import sys
import univention.testing as test
import univention.testing.udm as udm_test
import univention.testing.strings as uts

if __name__ == '__main__':
	sys.exit(131) # skip for now

	with udm_test.UCSTestUDM() as udm:
		dhcpService = udm.create_object('dhcp/service', service = uts.random_name())
		try:
			udm.create_object('dhcp/sharedsubnet', subnet = '10.20.30.0', subnetmask = '24', superordinate = dhcpService)
		except udm_test.UCSTestUDM_CreateUDMObjectFailed:
			sys.exit(0)

		test.fail('UDM did not report an error while trying to create a DHCP shared subnet with DHCP service as superordinate')
