# This file is auto-generated by the dh-umc tools and should not be edited!
msgid ""
msgstr ""
"Project-Id-Version: univention-management-console-module-appcenter\n"
"Report-Msgid-Bugs-To: packages@univention.de\n"
"POT-Creation-Date: 2016-08-18 16:57+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: \n"

#: umc/python/appcenter/util.py:160
#, python-format
msgid ""
"%s could not be downloaded. This seems to be a problem with the App Center "
"server. Please try again later."
msgstr ""

#: umc/python/appcenter/__init__.py:366
#, python-format
msgid "%s: Running tests"
msgstr ""

#: umc/python/appcenter/__init__.py:202
msgid ""
"A conflict between the system network settings and the docker bridge default"
" network has been detected."
msgstr ""

#: umc/python/appcenter/__init__.py:565 umc/python/appcenter/__init__.py:713
msgid "Another package operation is in progress"
msgstr ""

#: umc/python/appcenter/sanitizers.py:80
#, python-format
msgid "Any of %r must be given"
msgstr ""

#: umc/python/appcenter/sanitizers.py:52 umc/python/appcenter/sanitizers.py:56
#: umc/python/appcenter/sanitizers.py:60
msgid "Cannot connect to the LDAP service."
msgstr ""

#: umc/python/appcenter/__init__.py:237 umc/python/appcenter/__init__.py:252
#: umc/python/appcenter/__init__.py:438
#, python-format
msgid "Could not find an application for %s"
msgstr ""

#: umc/python/appcenter/app_center.py:133
#, python-format
msgid "Error while contacting the App Center server. %s"
msgstr ""

#: umc/python/appcenter/__init__.py:386
#, python-format
msgid "Installing %s"
msgstr ""

#: umc/python/appcenter/app_center.py:1631
#, python-format
msgid "Installing LDAP packages on %s"
msgstr ""

#: umc/python/appcenter/__init__.py:190 umc/python/appcenter/__init__.py:218
msgid ""
"Make sure docker.io is installed, try starting the service with \"service "
"docker start\"."
msgstr ""

#: umc/python/appcenter/sanitizers.py:60
msgid "Maybe the machine password changed during the session."
msgstr ""

#: umc/python/appcenter/sanitizers.py:56
msgid "Maybe your password changed during the session."
msgstr ""

#: umc/python/appcenter/__init__.py:80
msgid "Package not found in repository"
msgstr ""

#: umc/python/appcenter/sanitizers.py:52
msgid "Please check the join state of the machine."
msgstr ""

#: umc/python/appcenter/__init__.py:203
msgid ""
"Please either configure a different network for the docker bridge by setting"
" the UCR variable docker/daemon/default/opts/bip to a different network and "
"restart the system,"
msgstr ""

#: umc/python/appcenter/app_center.py:1545
msgid ""
"Registration of the application in LDAP failed. It will be retried every "
"time the App Center module is opened."
msgstr ""

#: umc/python/appcenter/app_center.py:1082
#, python-format
msgid ""
"The application needs a %(needs)s-bit operating system. This server is "
"running a %(has)s-bit operating system."
msgstr ""

#: umc/python/appcenter/sanitizers.py:56 umc/python/appcenter/sanitizers.py:60
msgid "The credentials provided were not accepted."
msgstr ""

#: umc/python/appcenter/__init__.py:190
msgid ""
"The docker service is not running! The App Center will not work properly."
msgstr ""

#: umc/python/appcenter/sanitizers.py:52
msgid "The server seems to be lacking a proper password file."
msgstr ""

#: umc/python/appcenter/sanitizers.py:90
msgid "There already is a component with this name"
msgstr ""

#: umc/python/appcenter/__init__.py:909
msgid ""
"There is no repository at this server (or at least none for the current UCS "
"version)"
msgstr ""

#: umc/python/appcenter/util.py:162
msgid "This is a problem with the App Center server. Please try again later."
msgstr ""

#: umc/python/appcenter/util.py:176
#, python-format
msgid ""
"This is probably due to the DNS settings of your server. You may find help "
"at %s."
msgstr ""

#: umc/python/appcenter/util.py:173
#, python-format
msgid ""
"This may be a problem with the firewall or proxy of your system. You may "
"find help at %s."
msgstr ""

#: umc/python/appcenter/sanitizers.py:56 umc/python/appcenter/sanitizers.py:60
msgid "This may be solved by simply logging out and in again."
msgstr ""

#: umc/python/appcenter/__init__.py:218
msgid "Unable to start the docker service!"
msgstr ""

#: umc/python/appcenter/__init__.py:389
#, python-format
msgid "Uninstalling %s"
msgstr ""

#: umc/python/appcenter/__init__.py:391
#, python-format
msgid "Upgrading %s"
msgstr ""

#: umc/python/appcenter/util.py:172
#, python-format
msgid ""
"https://docs.software-univention.de/manual-%s.html#ip-"
"config:Web_proxy_for_caching_and_policy_management__virus_scan"
msgstr ""

#: umc/python/appcenter/util.py:175
#, python-format
msgid "https://docs.software-univention.de/manual-%s.html#networks:dns"
msgstr ""

#: umc/python/appcenter/__init__.py:757
msgid "installed"
msgstr ""

#: umc/python/appcenter/__init__.py:759
msgid "not installed"
msgstr ""

#: umc/python/appcenter/__init__.py:204
msgid ""
"or disable the docker support in the AppCenter by setting appcenter/docker "
"to false."
msgstr ""

#: umc/python/appcenter/__init__.py:755
msgid "upgradable"
msgstr ""
