product: ucs
release: "4.4"
version: [1]
scope: ucs_4.4-0-errata4.4-1
src: univention-python
fix: 12.0.0-15A~4.4.0.201908121615
desc: |
 This update addresses the following issue:
 * Situations where operations are performed during a restart of the
   OpenLDAP server will trigger a reconnection in the uldap.py utilities.
bug: [47926]
erratum: 231
announced: 2019-08-14
