# This file is auto-generated by the dh-umc tools and should not be edited!
msgid ""
msgstr ""
"Project-Id-Version: univention-management-console-module-adconnector\n"
"Report-Msgid-Bugs-To: packages@univention.de\n"
"POT-Creation-Date: 2014-07-28 15:22+0200\n"
"PO-Revision-Date: 2011-11-09 15:54+0100\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: unicode\n"

#: umc/python/adconnector/__init__.py:286
msgid "Active Directory Connector is already running. Nothing to do."
msgstr ""
"Der Active Directory Connector ist bereits aktiv. Keine Aktion notwendig."

#: umc/python/adconnector/__init__.py:288
msgid "Active Directory Connector is already stopped. Nothing to do."
msgstr ""
"Der Active Directory Connector ist bereits gestoppt. Keine Aktion notwendig."

#: umc/python/adconnector/__init__.py:308
msgid "Active Directory connection service has been started."
msgstr "Der Active Directory-Verbindungsdienst wurde gestartet."

#: umc/python/adconnector/__init__.py:310
msgid "Active Directory connection service has been stopped."
msgstr "Der Active Directory-Verbindungsdienst wurde gestoppt."

#: umc/python/adconnector/__init__.py:177
msgid ""
"Active Directory connection settings have been saved and a new certificate "
"for the Active Directory server has been created."
msgstr ""
"Die Active Directory-Verbinungseinstellungen wurden gespeichert und ein "
"neues Zertifikat wurde für den Active Directory Server erzeugt."

#: umc/python/adconnector/__init__.py:169
msgid "Active Directory connection settings have been saved."
msgstr "Die Active Directory-Verbinungseinstellungen wurden gespeichert"

#: umc/python/adconnector/__init__.py:442
msgid "An error occurred while installing necessary software components."
msgstr ""

#: umc/python/adconnector/__init__.py:396
#, python-format
msgid "An unexpected error occurred: %s"
msgstr ""

#: umc/python/adconnector/__init__.py:254
msgid "Certificate has been uploaded successfully."
msgstr "Zertifikat wurde erfolgreich installiert."

#: umc/python/adconnector/__init__.py:258
msgid "Certificate upload or conversion failed."
msgstr "Zertifikatsinstallation oder -konvertierung fehlgeschlagen."

#: umc/python/adconnector/__init__.py:422
msgid "Configuring Administrator account..."
msgstr ""

#: umc/python/adconnector/__init__.py:447
msgid "Configuring DNS entries..."
msgstr ""

#: umc/python/adconnector/__init__.py:413
msgid "Configuring DNS server..."
msgstr ""

#: umc/python/adconnector/__init__.py:418
msgid "Configuring Kerberos settings..."
msgstr ""

#: umc/python/adconnector/__init__.py:454
msgid "Configuring SSL settings..."
msgstr ""

#: umc/python/adconnector/__init__.py:425
msgid "Configuring reverse DNS settings..."
msgstr ""

#: umc/python/adconnector/__init__.py:428
msgid "Configuring software components..."
msgstr ""

#: umc/python/adconnector/__init__.py:450
msgid "Configuring synchronization from AD..."
msgstr ""

#: umc/python/adconnector/__init__.py:409
msgid "Configuring time synchronization..."
msgstr ""

#: umc/python/adconnector/__init__.py:351
#: umc/python/adconnector/__init__.py:465
#, python-format
msgid ""
"Could not connect to AD Server %s. Please verify that the specified address "
"is correct."
msgstr ""

#: umc/python/adconnector/__init__.py:357
#: umc/python/adconnector/__init__.py:469
#, python-format
msgid ""
"Could not connect to AD Server %s. Please verify that username and password "
"are correct."
msgstr ""

#: umc/python/adconnector/__init__.py:473
#, python-format
msgid ""
"Could not establish an encrypted connection. Either \"%r\" is not reachable "
"or does not support encryption."
msgstr ""

#: umc/python/adconnector/__init__.py:470
#, python-format
msgid ""
"Could not synchronize the time between the UCS system and the Active "
"Directory domain controller: %s"
msgstr ""

#: umc/python/adconnector/__init__.py:176
#, python-format
msgid "Creation of certificate failed (%s)"
msgstr "Erstellung eines neuen Zertifikats fehlgeschlagen (%s)"

#: umc/python/adconnector/__init__.py:471
msgid ""
"Failed to set the password of the UCS Administrator to the Active Directory "
"Administrator password."
msgstr ""

#: umc/python/adconnector/__init__.py:482
msgid "Join has been finished successfully."
msgstr ""

#: umc/python/adconnector/__init__.py:484
msgid "Join has been finished with errors."
msgstr ""

#: umc/python/adconnector/__init__.py:373
msgid "Joining UCS into Active Directory domain"
msgstr ""

#: umc/python/adconnector/__init__.py:444
msgid "Running Samba join script..."
msgstr ""

#: umc/python/adconnector/__init__.py:159
#, python-format
msgid "Saving bind password failed (filename=%(fn)s ; exception=%(exception)s)"
msgstr ""
"Speichern des Replikationspasswortes fehlgeschlagen (filename=%(fn)s ; "
"exception=%(exception)s)"

#: umc/python/adconnector/__init__.py:304
msgid "Switching running state of Active Directory Connector failed."
msgstr "Starten/Stoppen des Active Directory Connectors ist fehlgeschlagen."

#: umc/python/adconnector/__init__.py:348
#: umc/python/adconnector/__init__.py:463
msgid "The AD member mode cannot only be configured on a DC master server."
msgstr ""

#: umc/python/adconnector/__init__.py:211
msgid ""
"The LDAP base of the given Active Directory server could not be determined. "
"Maybe the full-qualified hostname is wrong or unresolvable."
msgstr ""
"Die LDAP-Basis des angegebenen Active Directory Servers konnte nicht "
"ermittelt werden. Vielleicht ist der vollqualifizierte Name falsch "
"geschrieben oder nicht auflösbar."

#: umc/python/adconnector/__init__.py:354
#: umc/python/adconnector/__init__.py:467
#, python-format
msgid ""
"The domain name of the AD Server (%(ad_domain)s) does not match the local "
"UCS domain name (%(ucs_domain)s). For the AD member mode, it is necessary to "
"setup a UCS system with the same domain name as the AD Server."
msgstr ""

#: umc/python/adconnector/__init__.py:291
#, python-format
msgid ""
"Unknown command (\"%s\") Please report error to your local administrator"
msgstr ""
"Unbekanntes Kommando (\"%s\"). Bitte den Fehler beim lokalen Administrator "
"melden."
