#!/usr/share/ucs-test/runner python
## desc: Univention-s4-connector dns ttl syncronisation
## exposure: dangerous
## packages:
##   - univention-config
##   - univention-directory-manager-tools
##   - univention-s4-connector
##   - dnsutils
## bugs:
##   - 23732
## versions:
##  3.2-0: skip


import univention.testing.udm as udm_test
import univention.testing.strings as uts
import univention.testing.utils as utils
import random
import dnstests
import s4connector


if __name__ == '__main__':
	with udm_test.UCSTestUDM() as udm:
		s4connector.exit_if_connector_not_running()
		random_zone = dnstests.random_zone()
		host = dnstests.get_hostname()
		random_ttl = random.randrange (1,10000)
		test_zone_dn = udm.create_object('dns/forward_zone', zone = random_zone, nameserver = host, zonettl = random_ttl)
		dnstests.check_ldap_object(test_zone_dn, 'Forward Zone TTL', 'dNSTTL', '%s'%random_ttl)
		s4connector.wait_for_sync(30)
		dnstests.test_dns_ttl(random_zone, random_ttl)
		dnstests.check_ldap_object(test_zone_dn, 'Forward Zone TTL', 'dNSTTL', '%s'%random_ttl)

	s4connector.wait_for_sync()
	## Removing a DNS zone triggers bind reload in postrun, better check:
	dnstests.fail_if_cant_resolve_own_hostname()	## wait up to 17 seconds
